      module mod_input
      !
      ! Author: Vesselin Kolev <vesso.kolev@gmail.com>
      ! Version: 2016021001
      !
      ! This module handles the input file and extracts from there
      ! the parameters of the simulation as well as the atomic
      ! coordinates.
      !
      use mod_t

      implicit none

      contains

      subroutine read_input(filename,atoms,params)
      !
      ! The subroutine parses the file filename and gets from there
      ! the atomic coordinates and descriptions (stores them in atoms)
      ! and the paramters of the simulation (stores them in params).
      ! The input file (supplied here by filename variable) have to be
      ! generated by calling the python script parse_the_input.py.
      !
      character(len=*), intent(in) :: filename
      type(atom_t), dimension(:), allocatable, intent(out) :: atoms
      type(param_t), intent(out) :: params
      integer(kind=int32) :: numatoms,i

      open(unit=1,file=filename,status="old",form="formatted")

      read(1,fmt="(3F9.3)") params%box(1),params%box(2),params%box(3)
      read(1,fmt="(2F12.8)") params%core_dist_el,params%core_dist_mem
      read(1,fmt="(2F12.8)") params%left_el_charge,&
       params%right_el_charge
      read(1,fmt="(2F8.3)") params%el_grid_dens_x,params%el_grid_dens_y
      read(1,fmt="(I12)") params%accept_proposals
      read(1,fmt="(I5)") params%num_box_img_layers
      read(1,fmt="(F12.8)") params%LJ_cutoff
      read(1,fmt="(F12.8)") params%left_mem_gap_pos
      read(1,fmt="(F12.8)") params%right_mem_gap_pos
      read(1,fmt="(I5)") params%N1

      params%left_el_gap_pos=params%core_dist_el
      params%right_el_gap_pos=params%box(3)-params%core_dist_el
      params%half_box=params%box/2

      allocate(atoms(params%N1))

      do i=1,params%N1
         read(1,fmt="(I5,A3,A4,3F8.3,2F12.8,I5,F8.3)") atoms(i)%anum,&
          atoms(i)%resname,atoms(i)%aname,atoms(i)%x,atoms(i)%y,&
          atoms(i)%z,atoms(i)%sigma,atoms(i)%eps,atoms(i)%spatial_grp,&
          atoms(i)%charge
      end do

      close(unit=1)

      end subroutine read_input

      end module mod_input

